# Generated by Django 5.0.2 on 2024-02-23 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef011c43-0db3-41b2-b5e0-5813e904eb03'), primary_key=True, serialize=False),
        ),
    ]
