# Generated by Django 5.0.2 on 2024-02-23 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44f0abca-703a-42ef-a6ed-5410a1ede4c7'), primary_key=True, serialize=False),
        ),
    ]
