# Generated by Django 5.0.2 on 2024-02-23 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ffe55ae-236d-4546-8d35-5bf3c11d0fa7'), primary_key=True, serialize=False),
        ),
    ]
